spring:
  banner:
    location: banner.txt
  mvc:
    async:
      request-timeout: -1

project-maintainer:
  projects:
    uris:

# TODO why does application crash without this?
springdoc:
  enable-spring-security: false


logging:
  level:
    com.vaadin.flow.server.frontend.TaskRunDevBundleBuild: debug